### PR TITLE
Added Documentation for setting up Repo in development mode.

### LINKED ISSUE #233: Add documentation for setting up repo for development
It was brought to our attention that this project doesn't have a file with instructions on setting up the project for development.

### PR DESCRIPTION
**Pull request by DARK-art108**
Updated Readme.md : Added documentation for setting up Repo in Development mode(A quick start guide)

Fixes #233

### CODE REVIEW

**Comment by DARK-art108** [comment]
Added docs for setting up the repo in development mode. #233

**Comment by castastrophe** [comment]
@DARK-art108 Please do not merge your own pull requests in future. It is bad practice to merge without a review.

**Comment by castastrophe** [comment]
I see this is your fork (sorry I’m on GitHub Mobile which obscures that a bit). Tag me in the PR when you’re ready for review.

**Comment by DARK-art108** [comment]
I have created one new pull request recently, @castastrophe

**Pull request merged**
